name: Build and Deploy

on:
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
      name: build app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Install dependencies
          run: |
            pip install datasette
            datasette install git-history
        - run: git-history
        - name: Create database
          run: ./create_db.sh
