name: Build and Deploy

on:
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  build:
      name: build app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - uses: superfly/flyctl-actions/setup-flyctl@master
        - name: Install dependencies
          run: |
            pip install datasette
            datasette install git-history datasette-publish-fly
        - name: Create database
          run: |
            git-history file listings.db galway_listings.json --id id --namespace listing --import datetime --import re --convert '
            from datetime import datetime
            for listing in json.loads(content)["listings"]:
                listing["listing"]["latitude"] = listing["listing"]["point"]["coordinates"][1]
                listing["listing"]["longitude"] = listing["listing"]["point"]["coordinates"][0]
                listing["listing"]["publishDateReadable"] = str(datetime.fromtimestamp(listing["listing"]["publishDate"]/1000))
                listing["listing"]["numericPrice"] = re.sub("[^0-9]", "", listing["listing"]["price"])
                yield listing["listing"]
            '
        - name: Publish to fly.io
          run: datasette publish fly listings.db --app="daft-history" --install datasette-cluster-map
